name: build mule project
on: workflow_dispatch
jobs:
  build-code:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      
      
      - name: Cache dependencies
        uses: actions/cache@v3
        
      #- name: install OpenJDK 17
      #  run: |
      #      sudo apt-get update && sudo apt-get install openjdk-17-jdk
      #      sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      #      sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
      #      java -version
      #      echo "installed latest java version"
            
      - name: create properties
        env:
            UNAME: ${{ secrets.TEST_UNAME }}
            UPASS: ${{ secrets.TEST_UPASS }}
            BNAME: ${{ env.BRANCH_NAME }}
            
        run: |
            echo "uname = ${UNAME}, upass = ${UPASS} Branch = ${BNAME}"
      
