name: build mule project
on: workflow_dispatch
jobs:
  build-code:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      
      
      - name: Cache dependencies
        uses: actions/cache@v3
        
      #- name: install OpenJDK 17
      #  run: |
      #      sudo apt-get update && sudo apt-get install openjdk-17-jdk
      #      sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
      #      sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
      #      java -version
      #      echo "installed latest java version"
                  
      
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: getversion
      
      - name: Extract Maven project version
        run: echo ::set-output name=artifactId::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)
        id: getartifactId

      
      - name: set properties
        env:
            UNAME: ${{ secrets.TEST_UNAME }}
            UPASS: ${{ secrets.TEST_UPASS }}
            GITHUB_BRANCH: ${{ github.ref_name }}
            APPLICATION_NAME: ${{ steps.getartifactId.outputs.artifactId }}
            APPLICATION_VERSION: ${{ steps.getversion.outputs.version }}
        if: ('${GITHUB_BRANCH}' == 'dev')
        run: |
            echo "uname = ${UNAME} dev"
            echo "upass = ${UPASS} dev"
            echo "Branch = ${GITHUB_BRANCH} dev"
            echo "APP_Name = ${APPLICATION_NAME} dev"
            echo "APP_version = ${APPLICATION_VERSION} dev"
        elseif: ('${GITHUB_BRANCH}' == 'qa')
        run: |
            echo "uname = ${UNAME} qa"
            echo "upass = ${UPASS} qa"
            echo "Branch = ${GITHUB_BRANCH} qa"
            echo "APP_Name = ${APPLICATION_NAME} qa"
            echo "APP_version = ${APPLICATION_VERSION} qa"
        elseif: ('${GITHUB_BRANCH}' == 'PROD')
        run: |
            echo "uname = ${UNAME} PROD"
            echo "upass = ${UPASS} PROD"
            echo "Branch = ${GITHUB_BRANCH} PROD"
            echo "APP_Name = ${APPLICATION_NAME} PROD"
            echo "APP_version = ${APPLICATION_VERSION} PROD"
        else: 
        run: |
            echo "Branch name is unknown" 
